version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: MongoDB_Container
    hostname: mongodb_host
    ports:
      - '27017:27017'
    networks:
      - mongo_network
    restart: always

  diets:
    build:
      context: ./Diets
      dockerfile: Dockerfile
    container_name: Diets_Container
    ports:
      - '5002:5002'
    networks:
      - mongo_network
    depends_on:
      - mongodb
    restart: always

  meals:
    build:
      context: ./Meals
      dockerfile: Dockerfile
    container_name: Meals_Container
    ports:
      - '5001:5001'
    networks:
      - mongo_network
    depends_on:
      - diets
    restart: always

  nginx:
    build:
      context: ./NGINX
      dockerfile: Dockerfile
    container_name: NGINX_Container
    ports:
      - '5000:80'
    networks:
      - mongo_network
    depends_on:
      - meals
    restart: always

networks:
  mongo_network:
    driver: bridge