version: '3'

services:
  meals:
    build:
      context: ./Meals
    ports:
      - '5001:5001'
    depends_on:
      - diets
    container_name: Meals_Container

  diets:
    build:
      context: ./Diets
    container_name: Diets_Container
    ports:
      - '5002:5002'
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./MongoDB
    container_name: MongoDB_Container
    ports:
      - '27017:27017'

  nginx:
    build: ./NGINX
    container_name: NGINX_Container
    ports:
      - '80:80'
    depends_on:
      - meals
      - diets
      - mongodb
