version: '3'

services:
  meals:
    build:
      context: ./Meals
    ports:
      - '5001:5001'
    networks:
      - mongo-network
    depends_on:
      - diets
    container_name: Meals_Container
    restart: always

  diets:
    build:
      context: ./Diets
    container_name: Diets_Container
    ports:
      - '5002:5002'
    networks:
      - mongo-network
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: MongoDB_Container
    ports:
      - '27017:27017'
    networks:
      - mongo-network
    restart: always

  nginx:
    build: ./NGINX
    container_name: NGINX_Container
    ports:
      - '5000:80'
    networks:
      - mongo-network
    depends_on:
      - meals
    restart: always

networks:
  mongo-network: