version: '3'
services:
  meals:
    build:
      context: ./meals
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    depends_on:
      - diets
    container_name: Meals_Container
    restart: always

  diets:
    build:
      context: ./diets
      dockerfile: Dockerfile
    container_name: Diets_Container
    ports:
      - '5002:5002'
    depends_on:
      - mongodb
    restart: always

  mongodb:
    build:
      context: ./mongoDB
      dockerfile: Dockerfile
    container_name: MongoDB_Container
    ports:
      - '27017:27017'
    restart: always

  nginx:
    image: nginx:alpine
    container_name: NGINX_Container
    ports:
      - '80:80'
    depends_on:
      - meals
    restart: always
