version: '3'
services:
  meals:
    build:
      context: ./Meals
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    depends_on:
      - diets
    container_name: Meals_Container
    restart: unless-stopped
    volumes:
      - 'meals_data:/app/data'
  diets:
    build:
      context: ./Diets
      dockerfile: Dockerfile
    container_name: Diets_Container
    ports:
      - '5002:5002'
    depends_on:
      - mongodb
    restart: unless-stopped
    volumes:
      - 'diets_data:/app/data'
  mongodb:
    build:
      context: ./MongoDB
      dockerfile: Dockerfile
    container_name: MongoDB_Container
    ports:
      - '27017:27017'
    restart: unless-stopped
    volumes:
      - 'mongodb_data:/data/db'
  nginx:
    image: nginx:alpine
    container_name: NGINX_Container
    ports:
      - "5000:80"
    depends_on:
      - meals
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
volumes:
  meals_data: null
  diets_data: null
  mongodb_data: null
